# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20161025_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
